#!/bin/bash
# Grabs the latest app code and restarts the server.

REPO_ROOT="$1"

GIT=`which git`
GIT_REMOTE='origin'
GIT_BRANCH='master'

SERVER_START='./start.sh'
SERVER_STOP='./stop.sh'

# Sanity checks.
[ ! -d "$REPO_ROOT" ] && echo 'Invalid server root directory.' && exit 1

# Go to the project root.
cd $REPO_ROOT

# Pull the latest from git.
$GIT pull $GIT_REMOTE $GIT_BRANCH > /dev/null
make update_submodules

# Restart the services.
cd ./server-node
$SERVER_STOP || echo 'Nothing to stop.'
$SERVER_START || echo 'Could not start the server.'

# Update the "current commit" file.
cd ../client
$GIT rev-parse HEAD > ./status.html
